### ISSUE TITLE
Thoughts on code organization.

### ISSUE THREAD

**Issue by johncclayton** [autopkg/gilbertpalau-recipes#1]
Hi Gilbert, 

Perhaps the FWTool should maybe be split out into a separate Git repo - as it'll get improvements over time and having hundreds of copies sounds like a recipe for "F.U.N" to me.  

I'd also like to move the lightning recipe into my repo eventually.  I had kinda figured that we'd get a few recipes together and make sure everything is solid before asking for my repo to be moved into the autopkg one.

**Comment by entepriseosx** [comment]
Hey John,

I did place the FWTool script in the repo because I was trying to get it to work... I'll take it off there, now that I fully understand how it works.

Lightning recipe I had done it a long time ago, while you were working on the tool.  I recently made it available because there was an article written in derflounder about free tools for imaging mac's.  If you want I can take it down as well.

As soon as I can get FileWave 10 fully running at univision I will start converting some recipes to see how they work... although, I was talking to Elliot Jordan and we were talking about programmatically produce filewave recipes based on existing download recipes, so it will FileWave admins a huge headstart in terms of available recipes.

This is going to be huge, I am pretty excited about all this.

**Comment by johncclayton** [comment]
no, its fine to have it up - more thinking longer term that we want to generally move to having scripts in a single place to make them easier to locate

Thank you,

John Clayton

## CTO

FileWave (Europe) GmbH
St. Gallerstrasse 1
CH - 9500 Wil

Phone: +41 71 914 30 80
Fax: +41 71 914 30 81
Web: www.filewave.com http://www.filewave.com/
Skype: johncclayton

**Comment by tempusthales** [comment]
yeah I think FileWave should have its own repo, I think that would be
useful =)

On Mon, Sep 28, 2015 at 7:17 AM, John Clayton notifications@github.com
wrote:

> no, its fine to have it up - more thinking longer term that we want to
> generally move to having scripts in a single place to make them easier to
> locate
> 
> Thank you,
> 
> John Clayton
> 
> ## CTO
> 
> FileWave (Europe) GmbH
> St. Gallerstrasse 1
> CH - 9500 Wil
> 
> Phone: +41 71 914 30 80
> Fax: +41 71 914 30 81
> Web: www.filewave.com http://www.filewave.com/
> Skype: johncclayton
> 
> > On 27 Sep 2015, at 18:31, entepriseosx notifications@github.com wrote:
> > 
> > Hey John,
> > 
> > I did place the FWTool script in the repo because I was trying to get it
> > to work... I'll take it off there, now that I fully understand how it works.
> > 
> > Lightning recipe I had done it a long time ago, while you were working
> > on the tool. I recently made it available because there was an article
> > written in derflounder about free tools for imaging mac's. If you want I
> > can take it down as well.
> > 
> > As soon as I can get FileWave 10 fully running at univision I will start
> > converting some recipes to see how they work... although, I was talking to
> > Elliot Jordan and we were talking about programmatically produce filewave
> > recipes based on existing download recipes, so it will FileWave admins a
> > huge headstart in terms of available recipes.
> > 
> > This is going to be huge, I am pretty excited about all this.
> > 
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/autopkg/gilbertpalau-recipes/issues/1#issuecomment-143574669
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/autopkg/gilbertpalau-recipes/issues/1#issuecomment-143727165
> .

## 

Gilbert J. Palau
gilbertpalau@gmail.com
http://gilbertopalau.com
